# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=0)),
                ('venue_id', models.CharField(db_index=True, editable=False, max_length=63)),
                ('name', models.CharField(max_length=255)),
                ('permalink', models.URLField(editable=False, max_length=255, unique=True)),
                ('lock_level', models.PositiveSmallIntegerField(default=0)),
                ('categories', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=63)),
                ('street', models.CharField(blank=True, max_length=63)),
                ('city', models.CharField(blank=True, max_length=63)),
                ('state', models.CharField(max_length=63)),
                ('country', models.CharField(max_length=63)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
                ('updated_on', models.DateTimeField(blank=True)),
                ('user_report_on', models.DateTimeField(blank=True)),
                ('is_residential', models.BooleanField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set([('name', 'number', 'street', 'city', 'state')]),
        ),
    ]
