# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='id',
        ),
        migrations.AlterField(
            model_name='place',
            name='venue_id',
            field=models.CharField(editable=False, max_length=63, primary_key=True, serialize=False),
        ),
    ]
