# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161031_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='user_report_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
