# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161031_1515'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set([]),
        ),
    ]
