# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161031_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='updated_by',
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
