# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161031_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('waze_id', models.CharField(max_length=63, unique=True)),
            ],
        ),
    ]
