# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20161101_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waze_id', models.CharField(max_length=63, unique=True)),
            ],
        ),
    ]
