# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='is_residential',
            new_name='isResidential',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='is_verified',
            new_name='isVerified',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='lock_level',
            new_name='lockLevel',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='updated_by',
            new_name='updatedBy',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='updated_on',
            new_name='updatedOn',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='user_report_on',
            new_name='userReportOn',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='venue_id',
            new_name='venueId',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='waze_id',
            new_name='wazeId',
        ),
    ]
