# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20161108_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='userReportOn',
        ),
        migrations.AddField(
            model_name='place',
            name='createdBy',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='place',
            name='createdOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='updateRequest',
            field=models.BooleanField(default=False),
        ),
    ]
