# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20161209_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='createdOn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='updatedOn',
            field=models.DateTimeField(null=True),
        ),
    ]
